(define (problem harry-prob1)
  (:domain harry)
  (:objects Sword Fang Wand Locket Cup 
  Voldemort Hogwarts Forest-Dean Ministry Gringotts Olivander 
  Chamber Forbidden-Forest)
  (:init (atplace Hogwarts) 
  (placeHas Forest-Dean Sword) 
  (placeHas Ministry Locket)
  (placeHas Gringotts Cup)
  (placeHas Chamber Fang)
  (placeHas Olivander Wand)
  (placeHas Forbidden-Forest Voldemort)
  (horcrux Locket)
  (horcrux Cup)
  (candestroy Sword Locket)
  (candestroy Fang Cup)
  (candestroy Wand Voldemort)
  )
  (:goal (and (killed Voldemort))))